### PR TITLE
Add google firebase to the project

### PR DESCRIPTION
**Pull request by Ef55**
Only the authentication module was added.

### CODE REVIEW

**Comment by Ef55** [comment]
If you want some other firebase library added, mention it.
List of all firebase libraries: https://firebase.google.com/docs/android/setup#available-libraries

**Comment by Sosol02** [comment]
Are these libs relevant to the PR? I'll add them on my own I assume if I need them for the db.

**Comment by Sosol02** [comment]
LGTM, I assume you know what you're doing XD

**Review by Sosol02 — APPROVED** [review]
Okay, faudra ouvrir une issue pour fix les warnings du CI mais sinon c ok.

**Review by justagoodguy-omega — APPROVED** [review]

**Pull request merged**
