### PR TITLE
Make day events list close automatically when there are no events

### PR DESCRIPTION
**Pull request by justagoodguy-omega**

### CODE REVIEW

**Review by Ef55 — CHANGES_REQUESTED** [review]
This modification is welcome, but there is a slight issue:
if you press "View events" on a day without any events, nothing happens.

In my opinion, the button should be clearly disabled/gone in this case (ev. with a message like "No events to display").

**Comment by justagoodguy-omega** [comment]
> 
> 
> This modification is welcome, but there is a slight issue:
> if you press "View events" on a day without any events, nothing happens.
> 
> In my opinion, the button should be clearly disabled/gone in this case (ev. with a message like "No events to display").

The thing it has been the case for a while now so we could change it but it isn't linked to this PR

**Comment by Ef55** [comment]
> > 
> > 
> > This modification is welcome, but there is a slight issue:
> > if you press "View events" on a day without any events, nothing happens.
> > 
> > In my opinion, the button should be clearly disabled/gone in this case (ev. with a message like "No events to display").
> 
> The thing it has been the case for a while now so we could change it but it isn't linked to this PR

The thing is that, before, there just was an empty list, but now there is nothing (gives the sensation that the button doesn't work).
Anyway, we'll fix this in a subsequent PR.

**Review by Ef55 — APPROVED** [review]

**Comment by justagoodguy-omega** [comment]
> 
> 
> > > This modification is welcome, but there is a slight issue:
> > > if you press "View events" on a day without any events, nothing happens.
> > > In my opinion, the button should be clearly disabled/gone in this case (ev. with a message like "No events to display").
> > 
> > 
> > The thing it has been the case for a while now so we could change it but it isn't linked to this PR
> 
> The thing is that, before, there just was an empty list, but now there is nothing (gives the sensation that the button doesn't work).
> Anyway, we'll fix this in a subsequent PR.

The thing is that nope, before it did the same thing, what you're thinking of is when the user deletes an event and there are no more remaining there used to be a blank screen which was indeed changed in this PR

**Comment by Ef55** [comment]
Oh ok, sorry about that; I wrongfully assumed that it was previously possible to open the blank page.

**Review by TheImpressiveDonut — APPROVED** [review]
Nice code, not much changed so I have nothing to say !

**Review by hugolan — APPROVED** [review]

**Pull request merged**
